apiVersion: v1
kind: Pod 
metadata:
  name: apache-deployment
  labels:
    name: apache-deployment 
    app: my-app 
spec:
  containers:
   - name: apache-deployment  
     image: 22050108_webimage:1.1
     ports:
        - containerPort: 8080
---     


apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service 
    app: my-app       
spec:
  type: NodePort
  ports:
     - port: 80
       targetPort: 80
       nodePort: 42000
  selector: 
    name: apache-deployment 
    app: my-app
